# Generated by Django 6.0.3 on 2026-03-22 03:49

import reactivated.constraints
import reactivated.fields
import server.drafts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', reactivated.fields.EnumField(default=server.drafts.models.Draft.Status['PENDING'], enum=server.drafts.models.Draft.Status)),
                ('subreddit_name', models.CharField(max_length=255)),
                ('post_title', models.CharField(max_length=500)),
                ('post_url', models.URLField(max_length=500, unique=True)),
                ('post_author', models.CharField(blank=True, max_length=255)),
                ('post_body', models.TextField(blank=True)),
                ('draft_reply', models.TextField(blank=True)),
                ('edited_reply', models.TextField(blank=True)),
                ('edit_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('alert_raw', models.TextField(blank=True)),
                ('matched_keyword', models.CharField(blank=True, max_length=255)),
                ('buy_upvotes', models.BooleanField(default=False)),
                ('action', reactivated.fields.EnumField(blank=True, enum=server.drafts.models.Draft.Action, null=True)),
                ('triage_reasoning', models.TextField(blank=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('upvotes_needed', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'constraints': [reactivated.constraints.EnumConstraint(field_name='action', members=['LINK', 'ADVICE_ONLY', 'REJECT'], name='drafts_draft_action_enum'), reactivated.constraints.EnumConstraint(field_name='status', members=['PENDING', 'APPROVED', 'REJECTED', 'POSTED'], name='drafts_draft_status_enum')],
            },
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('banned', models.BooleanField(default=False)),
                ('post_via', reactivated.fields.EnumField(default=server.drafts.models.Subreddit.PostVia['SELF'], enum=server.drafts.models.Subreddit.PostVia)),
                ('daily_limit', models.IntegerField(default=3)),
                ('weekly_limit', models.IntegerField(default=10)),
                ('competitors', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'constraints': [reactivated.constraints.EnumConstraint(field_name='post_via', members=['SELF', 'CROWDREPLY'], name='drafts_subreddit_post_via_enum')],
            },
        ),
    ]
