# Generated by Django 6.0.3 on 2026-03-23 15:47

import reactivated.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='draft',
            name='drafts_draft_status_enum',
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_reply_b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_reply_c',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=reactivated.constraints.EnumConstraint(field_name='status', members=['PENDING', 'APPROVED', 'REJECTED', 'POSTED', 'SKIPPED'], name='drafts_draft_status_enum'),
        ),
    ]
