# Generated by Django 6.0.3 on 2026-03-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_remove_draft_drafts_draft_status_enum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='selected_variant',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
